
modLoader="javafml"
loaderVersion="[47,)"
issueTrackerURL="https://github.com/Umpaz/NethersDelight/issues"
license="MIT License"

[[mods]]
modId="nethersdelight"
version="1.20.1-4.0"
displayName="Nether's Delight"
# updateJSONURL=""
displayURL="https://github.com/Umpaz/NethersDelight"
logoFile="logo.png"
logoBlur=false
credits="Umpaz, SoyTutta, and Sammy;"
authors="Umpaz, SoyTutta"
description="A nether expansion for the Farmer's Delight mod!"
itemIcon="nethersdelight:blackstone_stove"
configBackground="minecraft:textures/block/netherrack.png"

[[dependencies.nethersdelight]]
    modId="forge"
    mandatory=true
    versionRange="[47.1.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.nethersdelight]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"

[[dependencies.nethersdelight]]
    modId="farmersdelight"
    mandatory=true
    versionRange="[1.2.3,)"
    ordering="NONE"
    side="BOTH"
